-d C:\PROJECT\temp\hdmi_tx\hw\tn9k_hdmi\impl\gwsynthesis\hdmi_audio.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\PROJECT\temp\hdmi_tx\hw\tn9k_hdmi\src\tangnano9k.cst
-cfg C:\PROJECT\temp\hdmi_tx\hw\tn9k_hdmi\impl\pnr\device.cfg
-sdc C:\PROJECT\temp\hdmi_tx\hw\tn9k_hdmi\src\tangnano9k.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
